import { Head, Link, router, useForm } from '@inertiajs/react';
import { ArrowLeft, Boxes, PackagePlus, PencilLine, TriangleAlert } from 'lucide-react';
import type { FormEvent, ReactNode } from 'react';

type InventoryItem = { id: number; name: string; category: string; unit: string; quantity: number; reorder_level: number };
type Props = { items: InventoryItem[]; success?: string };

export default function InventoryIndex({ items, success }: Props) {
    const form = useForm({ name: '', category: '', unit: 'pieces', quantity: '0', reorder_level: '5' });

    function submit(event: FormEvent<HTMLFormElement>) {
        event.preventDefault();
        form.post('/inventory', { onSuccess: () => form.reset() });
    }

    function updateQuantity(item: InventoryItem) {
        const quantity = window.prompt(`Update quantity for ${item.name}`, String(item.quantity));
        if (quantity !== null && /^\d+$/.test(quantity)) router.patch(`/inventory/${item.id}/stock`, { quantity }, { preserveScroll: true });
    }

    return <><Head title="Inventory" /><main className="min-h-screen bg-[#dbe8e9] bg-[url('/campus-background.png')] bg-cover bg-center bg-fixed font-sans text-black"><div className="min-h-screen bg-white/45 p-3 sm:p-5 lg:p-7"><div className="mx-auto min-h-[calc(100vh-2rem)] max-w-[1500px]">
        <header className="mb-4 flex items-center justify-between rounded-[28px] border border-white/70 bg-white/60 px-5 py-4 shadow-[0_20px_55px_rgba(23,57,54,0.16)] backdrop-blur-xl sm:px-8"><div className="flex items-center gap-3"><img src="/brokenshire-logo.png" alt="Brokenshire Clinic" className="h-11 w-11 object-contain" /><div><p className="text-xs font-black uppercase tracking-widest text-[#075c49]">Clinic operations</p><h1 className="text-xl font-black uppercase sm:text-2xl">Inventory</h1></div></div><Link href="/dashboard" className="flex items-center gap-2 text-xs font-black uppercase text-[#075c49] hover:text-[#0b996e]"><ArrowLeft className="h-4 w-4" /><span className="hidden sm:inline">Dashboard</span></Link></header>
        {success && <div className="mb-4 rounded-2xl border border-[#8ad8bd] bg-[#e0f7ed]/90 px-5 py-3 text-sm font-bold text-[#075c49]">{success}</div>}
        <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_350px]"><section className="rounded-[28px] border border-white/70 bg-white/60 p-5 shadow-[0_20px_55px_rgba(23,57,54,0.16)] backdrop-blur-xl sm:p-8"><div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-2"><Boxes className="h-5 w-5 text-[#075c49]" /><h2 className="text-xl font-black uppercase sm:text-2xl">Stock Items</h2></div><span className="rounded-full bg-[#f8e4a8] px-3 py-1 text-xs font-black uppercase text-[#8a5b00]">{items.filter((item) => item.quantity <= item.reorder_level).length} low stock</span></div><div className="overflow-x-auto"><table className="w-full min-w-[38rem] text-left text-sm"><thead className="border-b border-black/15 text-xs font-black uppercase tracking-wide text-black/60"><tr><th className="px-3 py-3">Item</th><th className="px-3 py-3">Category</th><th className="px-3 py-3">Quantity</th><th className="px-3 py-3">Status</th><th className="px-3 py-3" /></tr></thead><tbody className="divide-y divide-black/10">{items.map((item) => { const low = item.quantity <= item.reorder_level; return <tr key={item.id}><td className="px-3 py-4 font-black">{item.name}</td><td className="px-3 py-4">{item.category}</td><td className="px-3 py-4 font-bold">{item.quantity} {item.unit}</td><td className="px-3 py-4"><span className={`inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-black uppercase ${low ? 'bg-[#f8e4a8] text-[#8a5b00]' : 'bg-[#b9e9d7] text-[#075c49]'}`}>{low && <TriangleAlert className="h-3 w-3" />}{low ? 'Low stock' : 'In stock'}</span></td><td className="px-3 py-4"><button type="button" onClick={() => updateQuantity(item)} className="rounded-lg bg-[#075c49] p-2 text-white" title="Update quantity"><PencilLine className="h-4 w-4" /></button></td></tr>; })}</tbody></table>{items.length === 0 && <p className="py-12 text-center text-sm font-black uppercase text-black/45">No inventory items recorded</p>}</div></section>
        <section className="rounded-[28px] border border-white/70 bg-white/60 p-5 shadow-[0_20px_55px_rgba(23,57,54,0.16)] backdrop-blur-xl sm:p-7"><div className="flex items-center gap-2"><PackagePlus className="h-5 w-5 text-[#075c49]" /><h2 className="text-xl font-black uppercase">Add Item</h2></div><form onSubmit={submit} className="mt-6 space-y-4">{(['name', 'category', 'unit'] as const).map((field) => <label key={field} className="block text-xs font-black uppercase tracking-wide text-black/65">{field}<input required value={form.data[field]} onChange={(event) => form.setData(field, event.target.value)} className="mt-1 w-full rounded-xl border border-black/20 bg-white/55 px-3 py-2.5 text-sm normal-case outline-none ring-[#0b996e] focus:ring-2" /></label>)}<div className="grid grid-cols-2 gap-3"><label className="block text-xs font-black uppercase tracking-wide text-black/65">Quantity<input required type="number" min="0" value={form.data.quantity} onChange={(event) => form.setData('quantity', event.target.value)} className="mt-1 w-full rounded-xl border border-black/20 bg-white/55 px-3 py-2.5 text-sm outline-none ring-[#0b996e] focus:ring-2" /></label><label className="block text-xs font-black uppercase tracking-wide text-black/65">Reorder level<input required type="number" min="0" value={form.data.reorder_level} onChange={(event) => form.setData('reorder_level', event.target.value)} className="mt-1 w-full rounded-xl border border-black/20 bg-white/55 px-3 py-2.5 text-sm outline-none ring-[#0b996e] focus:ring-2" /></label></div><button disabled={form.processing} type="submit" className="w-full rounded-xl bg-[#075c49] px-4 py-3 text-xs font-black uppercase text-white hover:bg-[#0b996e] disabled:opacity-60">{form.processing ? 'Saving...' : 'Add Inventory Item'}</button></form></section></div>
    </div></div></main></>;
}

InventoryIndex.layout = (page: ReactNode) => page;
